### ISSUE TITLE
open graph / twitter card meta 

### ISSUE THREAD

**Issue by franswan** [boringprotocol/blog#5]
per page or post with frontmatter data (images, descrips, title, etc...)

be sure all social sharing previews are looking good

**Comment by redmanbravemm** [comment]
Do we already have the images we want to use  as previews for OGP and Twitter cards?

**Comment by franswan** [comment]
We might make featuredImage in frontmatter to specify image path and conditionally point to a default BOP image when not featured image is present.

The other fields also might conditionally have a fallback to generic content. 

So, no. No images exist as of yet.

**Comment by redmanbravemm** [comment]
Title, description and permalink must be mandatory when defining YAML info for each page. 
I've added the permalink property for some pages that were missing it.

This issue should remain in progress until we complete the following steps:
- [ ] Fill the FaceBook ID `fb:app_id` *1
- [ ] Design and add a proper global featured image that will act as a fallback whenever page featuredImage is missing
- [ ] Once we have a design, fill the alternate text for that global site featured image fallback

*1 According to johnbushea's [HEAD list,](https://github.com/joshbuchea/HEAD) a FB id must be added when it comes to OGP

---

Here's how the absolute URL is built for both OGP and Twitter cards:
<img width="595" alt="Screenshot 2021-07-31 at 23 18 01" src="https://user-images.githubusercontent.com/88066581/127751573-41555a28-d081-4e0e-bac8-3834a1df1d93.png">

... successfully rendering something like:
<img width="521" alt="Screenshot 2021-07-31 at 23 25 40" src="https://user-images.githubusercontent.com/88066581/127751707-80edd404-dd5f-4a28-a49d-b0247258f996.png">

The above solution works as expected, bot not in the following situation (/blog/):
<img width="798" alt="Screenshot 2021-07-31 at 23 24 04" src="https://user-images.githubusercontent.com/88066581/127751658-d6a10b99-a0a7-4c33-99a0-34e88030b60c.png">

Would need some help here to tackle this situation too. Let me know your thoughts please when you have some time.
